version: '3'

tasks:
  default:
    cmds:
      - task: update

  update:
    cmds:
      - go run ./cmd/fs_generator/ -name microboiler_grpc_server -src ../microboiler_grpc_server/
      - go run ./cmd/fs_generator/ -name microboiler_rest_server -src ../microboiler_rest_server/
      - go run ./cmd/fs_generator/ -name microboiler_kafka_producer -src ../microboiler_kafka_producer/

  run:
    cmds:
      - go run ./cmd/microboiler/

  build:
    cmds:
      - go build -o bin/fs_generator ./cmd/fs_generator
      - go build -o bin/microboiler ./cmd/microboiler

  check:
    deps:
      - update
    cmds:
      - rm -rf /tmp/some/check
      - go run ./cmd/microboiler/ -name check -opt microboiler_grpc_server -opt microboiler_rest_server -opt microboiler_kafka_producer -output /tmp/some/

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...

