version: '3'

tasks:
  default:
    cmds:
      - task: build

  update:
    cmds:
      - go run ./cmd/fs_generator/ ../microboiler_grpc_server/ cmd/microboiler/microboiler_grpc_server.yml yml
      - go run ./cmd/fs_generator/ ../microboiler_rest_server/ cmd/microboiler/microboiler_rest_server.yml yml

  run:
    cmds:
      - go run ./cmd/microboiler/

  build:
    desc: Build the server
    cmds:
      - go build -o bin/microboiler ./cmd/microboiler

  lint:
    desc: Run linter
    cmds:
      - go fmt ./...
      - go vet ./...

